#!/usr/bin/env bash
# installs and starts nginx with custom index page; Configures Nginx server to have a custom 404 page

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i 's@#error_page 404 /404.html;@error_page 404 /404.html;\n    location = /404.html {\n  root /var/www/html;\n   internal;\n    }\n}@' /etc/nginx/sites-enabled/default

#Configures Nginx so that its HTTP response contains a custom header X-Served-By with its value being the hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i '/server_name _;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo service nginx restart
