#!/usr/bin/env bash
#installing HAproxy on & configuring lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

#config file
server_config=\
"
frontend iomititi-frontend
	bind *:80
	mode http
	default_backend iomititi-backend
backend iomititi-backend
	balance roundrobin
	server 126477-web-01 52.86.37.113:80 check
	server 126477-web-02 3.83.227.64:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

#enabling init
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
